security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        App\Entity\Doctor:
            algorithm: bcrypt

    providers:
        api_doctor_provider:
            entity:
                class: App\Entity\Doctor
                property: apiKey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        api_doctor:
#            pattern: ^/api/doctor
#            anonymous: false
#            stateless: true
#            provider: api_doctor_provider

#            guard:
#                authenticators:
#                    - api_key_authenticator

        main:
            anonymous: ~

    access_control:
        # - { path: ^/api/doctor, roles: ROLE_DOCTOR }
        # - { path: ^/profile, roles: ROLE_USER }
