parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    api_doctor_authenticator:
        class: App\Security\DoctorTokenAuthenticator
        public: true

    api_user_authenticator:
        class: App\Security\UserTokenAuthenticator
        public: true